/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef hello_world_CONSTANTS_H
#define hello_world_CONSTANTS_H

#include "hello_world_types.h"



class hello_worldConstants {
 public:
  hello_worldConstants();

};

extern const hello_worldConstants g_hello_world_constants;



#endif
