/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "hello_world_constants.h"



const hello_worldConstants g_hello_world_constants;

hello_worldConstants::hello_worldConstants() {
}



