/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef proxy_server_CONSTANTS_H
#define proxy_server_CONSTANTS_H

#include "proxy_server_types.h"



class proxy_serverConstants {
 public:
  proxy_serverConstants();

};

extern const proxy_serverConstants g_proxy_server_constants;



#endif
