/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "proxy_server_constants.h"



const proxy_serverConstants g_proxy_server_constants;

proxy_serverConstants::proxy_serverConstants() {
}



