/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef proxy_server_H
#define proxy_server_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "proxy_server_types.h"



#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class proxy_serverIf {
 public:
  virtual ~proxy_serverIf() {}
  virtual void get_page(std::string& _return, const std::string& url) = 0;
};

class proxy_serverIfFactory {
 public:
  typedef proxy_serverIf Handler;

  virtual ~proxy_serverIfFactory() {}

  virtual proxy_serverIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(proxy_serverIf* /* handler */) = 0;
};

class proxy_serverIfSingletonFactory : virtual public proxy_serverIfFactory {
 public:
  proxy_serverIfSingletonFactory(const boost::shared_ptr<proxy_serverIf>& iface) : iface_(iface) {}
  virtual ~proxy_serverIfSingletonFactory() {}

  virtual proxy_serverIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(proxy_serverIf* /* handler */) {}

 protected:
  boost::shared_ptr<proxy_serverIf> iface_;
};

class proxy_serverNull : virtual public proxy_serverIf {
 public:
  virtual ~proxy_serverNull() {}
  void get_page(std::string& /* _return */, const std::string& /* url */) {
    return;
  }
};

typedef struct _proxy_server_get_page_args__isset {
  _proxy_server_get_page_args__isset() : url(false) {}
  bool url :1;
} _proxy_server_get_page_args__isset;

class proxy_server_get_page_args {
 public:

  proxy_server_get_page_args(const proxy_server_get_page_args&);
  proxy_server_get_page_args& operator=(const proxy_server_get_page_args&);
  proxy_server_get_page_args() : url() {
  }

  virtual ~proxy_server_get_page_args() throw();
  std::string url;

  _proxy_server_get_page_args__isset __isset;

  void __set_url(const std::string& val);

  bool operator == (const proxy_server_get_page_args & rhs) const
  {
    if (!(url == rhs.url))
      return false;
    return true;
  }
  bool operator != (const proxy_server_get_page_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const proxy_server_get_page_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class proxy_server_get_page_pargs {
 public:


  virtual ~proxy_server_get_page_pargs() throw();
  const std::string* url;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _proxy_server_get_page_result__isset {
  _proxy_server_get_page_result__isset() : success(false) {}
  bool success :1;
} _proxy_server_get_page_result__isset;

class proxy_server_get_page_result {
 public:

  proxy_server_get_page_result(const proxy_server_get_page_result&);
  proxy_server_get_page_result& operator=(const proxy_server_get_page_result&);
  proxy_server_get_page_result() : success() {
  }

  virtual ~proxy_server_get_page_result() throw();
  std::string success;

  _proxy_server_get_page_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const proxy_server_get_page_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const proxy_server_get_page_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const proxy_server_get_page_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _proxy_server_get_page_presult__isset {
  _proxy_server_get_page_presult__isset() : success(false) {}
  bool success :1;
} _proxy_server_get_page_presult__isset;

class proxy_server_get_page_presult {
 public:


  virtual ~proxy_server_get_page_presult() throw();
  std::string* success;

  _proxy_server_get_page_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class proxy_serverClient : virtual public proxy_serverIf {
 public:
  proxy_serverClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  proxy_serverClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void get_page(std::string& _return, const std::string& url);
  void send_get_page(const std::string& url);
  void recv_get_page(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class proxy_serverProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<proxy_serverIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (proxy_serverProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_get_page(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  proxy_serverProcessor(boost::shared_ptr<proxy_serverIf> iface) :
    iface_(iface) {
    processMap_["get_page"] = &proxy_serverProcessor::process_get_page;
  }

  virtual ~proxy_serverProcessor() {}
};

class proxy_serverProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  proxy_serverProcessorFactory(const ::boost::shared_ptr< proxy_serverIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< proxy_serverIfFactory > handlerFactory_;
};

class proxy_serverMultiface : virtual public proxy_serverIf {
 public:
  proxy_serverMultiface(std::vector<boost::shared_ptr<proxy_serverIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~proxy_serverMultiface() {}
 protected:
  std::vector<boost::shared_ptr<proxy_serverIf> > ifaces_;
  proxy_serverMultiface() {}
  void add(boost::shared_ptr<proxy_serverIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void get_page(std::string& _return, const std::string& url) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get_page(_return, url);
    }
    ifaces_[i]->get_page(_return, url);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class proxy_serverConcurrentClient : virtual public proxy_serverIf {
 public:
  proxy_serverConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  proxy_serverConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void get_page(std::string& _return, const std::string& url);
  int32_t send_get_page(const std::string& url);
  void recv_get_page(std::string& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif



#endif
